---
spring:
  output:
    ansi:
      enabled: always
  profiles:
    include:
    - db
logging:
  level:
    jdbc: 'debug'
    org.springframework.jdbc: 'debug'
---
spring:
  profiles: db
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    initialization-mode: always
    schema:
    - classpath*:/db/migration/V2020042100__drop_schema.sql
    - classpath*:/db/migration/V2020042101__create_schema.sql
    data:
    - classpath*:/db/migration/V2020042102__data.sql
---
spring:
  profiles: ci
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        #include: >
        #  shutdown,
        #  health
---
