name: CI
on: [push]
env:
  SPRING_PROFILES_ACTIVE: ci
jobs:
  step-0-application-without-security:
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} step-0-application-without-security
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.node
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
    #- run: hash docker 2>/dev/null || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
    - run: sudo apt-get install -y httpie
    - run: npm i -g wait-port
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-0-application-without-security
    - run: ( bash $GITHUB_WORKSPACE/step-0-application-without-security/target/*jar --spring.profiles.active=ci & ) || echo ...
    - run: wait-port 8080
    - run: http get :8080
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-0-test-application-without-security -Dgroups=e2e
    - run: http --ignore-stdin post :8080/actuator/shutdown
  step-1-application-with-default-spring-security:
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} step-1-application-with-default-spring-security
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/cache@v1
      with:
        path: ~/.node
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-docker-
          ${{ runner.os }}-maven-
          ${{ runner.os }}-node-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: type docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }
    - run: sudo apt-get install -y httpie
    - run: npm i -g wait-port
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-1-application-with-default-spring-security
    - run: ( bash $GITHUB_WORKSPACE/step-1-application-with-default-spring-security/target/*jar & ) || echo ...
    - run: wait-port 8080
    - run: http get :8080
    - run: cd $GITHUB_WORKSPACE && ./mvnw -f step-1-test-application-with-default-spring-security -Dgroups=e2e -Pci
    - run: http --ignore-stdin -a user:pwd post :8080/actuator/shutdown
